/**
 * AI Configuration for Edge Function
 *
 * ⚠️ SYNC WARNING ⚠️
 * ==================
 * This file is DUPLICATED from the frontend and must be manually synced.
 *
 * SOURCE OF TRUTH: src/config/aiConfig.ts (edit that one, NOT this file)
 * SYNCED TO:       supabase/functions/ai-notes-check/config.ts (THIS FILE)
 *
 * WHY: Edge Functions cannot import from src/ directory (Deno runtime limitation)
 *
 * DO NOT EDIT THIS FILE DIRECTLY - edit src/config/aiConfig.ts instead!
 * After editing frontend config, run: npm run deploy:edge
 *
 * FUTURE: Consider moving to database-backed config or build-time sync script
 */

// ============================================================================
// AI Configuration Constants
// ============================================================================

export const AI_CONFIG = {
  /**
   * AI Model to use for notes analysis
   * Claude Haiku 4.5: Fast, cost-effective, suitable for frequent use
   */
  MODEL: 'claude-haiku-4-5-20251001' as const,

  /**
   * Comment constraints
   */
  MAX_COMMENT_LENGTH: 200, // Keep suggestions concise and actionable
  MIN_SELECTED_TEXT_LENGTH: 5, // Minimum characters for text anchoring (prevents ambiguous matches)
  MAX_RETRY_ATTEMPTS: 3, // Maximum retry attempts for text matching failures

  /**
   * Processing limits
   */
  MAX_COMMENTS_PER_RUN: 20, // Prevent excessive API costs and overwhelming suggestions

  /**
   * System Prompt
   * Defines AI role, task, constraints, and rules
   */
  SYSTEM_PROMPT: `Act as an expert analyst specializing in improving educational notes. You have a keen eye for identifying missing insights, clarity issues, and organizational improvements. Your focus is on providing high-value, non-redundant suggestions.

Your objective: Meticulously analyze the user's notes alongside the source material (transcript/description) and identify the most critical improvements.

Follow these guidelines:
- Before suggesting anything, carefully review ALL existing AI suggestions to avoid redundancy
- Do NOT suggest something if a similar point has already been made (even if worded differently)
- For example: If an existing comment says "Add more context about X", don't suggest "Clarify X" or "Explain X better"
- Prioritize quality over quantity - only suggest what genuinely adds value
- For selected-text comments: Copy text EXACTLY from notes (character-for-character, including punctuation)
- Keep each suggestion under 200 characters - be concise and actionable
- Focus on substance: missing key concepts, unclear phrasing, factual errors, poor structure

Suggestion Types:
- missing_concept: Key topics from source material not captured in notes
- rewording: Clearer, more precise phrasing for existing text
- factual_correction: Potential inaccuracies compared to source
- structural_suggestion: Better organization or formatting

Category Types:
- selected_text: Anchored to specific passage (provide exact quoted text, min 5 chars)
- general: Broad observation not tied to specific text

Output Format: Return valid JSON only (no markdown fences, no explanations).

Take a deep breath and work on this problem step-by-step.`,

  /**
   * JSON Schema Instructions
   * Specifies exact structure AI must return
   */
  JSON_SCHEMA_INSTRUCTIONS: `Return a JSON object with this exact structure:

{
  "comments": [
    {
      "category": "general" | "selected_text",
      "suggestionType": "missing_concept" | "rewording" | "factual_correction" | "structural_suggestion",
      "body": "Your suggestion (max 200 chars)",
      "selectedText": "exact text from notes" | null
    }
  ]
}

RULES:
- "selectedText" is required (non-null) if category is "selected_text"
- "selectedText" must be null if category is "general"
- "body" must be under 200 characters
- "selectedText" must be minimum 5 characters if provided
- Return empty array if no suggestions needed`,
} as const;

// ============================================================================
// Metadata Configuration
// ============================================================================

export const AI_METADATA_CONFIG: Record<string, string[]> = {
  'short-video': [
    'description',
    'author',
    'creator',
    'channelName',
    'handle',
    'transcript',
    'platform',
    'url',
    'normalizedUrl',
    'duration',
    'viewCount',
    'likeCount',
    'publishedAt',
  ],
  video: [
    'description',
    'transcript',
    'author',
    'creator',
    'channelName',
    'platform',
    'duration',
    'url',
    'normalizedUrl',
    'viewCount',
    'likeCount',
    'publishedAt',
  ],
  book: [
    'description',
    'author',
    'year',
    'publisher',
    'isbn',
    'pageCount',
    'url',
  ],
  article: [
    'url',
    'author',
    'platform',
    'description',
    'publishedAt',
    'siteName',
  ],
  podcast: [
    'description',
    'transcript',
    'creator',
    'platform',
    'duration',
    'url',
    'publishedAt',
    'episodeNumber',
    'showName',
  ],
} as const;

/**
 * Extract AI-relevant metadata from a resource
 */
export function getAIMetadataForResource(resource: Record<string, unknown>): Record<string, unknown> {
  const type = resource.type as string;
  const fields = AI_METADATA_CONFIG[type] || [];

  const metadata: Record<string, unknown> = {};

  for (const field of fields) {
    const value = resource[field];
    if (value !== null && value !== undefined && value !== '') {
      metadata[field] = value;
    }
  }

  return metadata;
}
